"""initial

Revision ID: fb6cdd34ba8b
Revises: 
Create Date: 2026-03-17 00:55:29.604101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb6cdd34ba8b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instruments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('market', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('pip_size', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_instruments_symbol'), ['symbol'], unique=True)

    op.create_table('macro_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('indicator_name', sa.String(length=64), nullable=False),
    sa.Column('country', sa.String(length=8), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('previous_value', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('forecast_value', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('release_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('indicator_name', 'country', 'release_date', name='uix_macro_data')
    )
    op.create_table('news_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('headline', sa.String(length=512), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sentiment_score', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('importance', sa.String(length=16), nullable=False),
    sa.Column('related_instruments', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('news_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_news_events_published_at'), ['published_at'], unique=False)

    op.create_table('accuracy_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('period', sa.String(length=32), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('instrument_id', sa.Integer(), nullable=True),
    sa.Column('market', sa.String(length=16), nullable=True),
    sa.Column('timeframe', sa.String(length=8), nullable=True),
    sa.Column('total_signals', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('breakevens', sa.Integer(), nullable=False),
    sa.Column('win_rate', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('profit_factor', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('avg_win_pips', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('avg_loss_pips', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('sharpe_ratio', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('max_drawdown_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('expectancy', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_data',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('high', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('low', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('close', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('volume', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'timeframe', 'timestamp', name='uix_price_data')
    )
    with op.batch_alter_table('price_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_data_instrument_id'), ['instrument_id'], unique=False)
        batch_op.create_index('ix_price_data_instrument_timeframe', ['instrument_id', 'timeframe'], unique=False)
        batch_op.create_index('ix_price_data_timestamp', ['timestamp'], unique=False)

    op.create_table('signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('signal_strength', sa.String(length=16), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('stop_loss', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('take_profit_1', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('take_profit_2', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('risk_reward', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('position_size_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('composite_score', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('ta_score', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('fa_score', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('sentiment_score', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('geo_score', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('horizon', sa.String(length=32), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('indicators_snapshot', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signals_instrument_id'), ['instrument_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_status'), ['status'], unique=False)

    op.create_table('signal_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('entry_filled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('entry_actual_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('exit_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('exit_reason', sa.String(length=16), nullable=True),
    sa.Column('pnl_pips', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('pnl_percent', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('result', sa.String(length=16), nullable=True),
    sa.Column('max_favorable_excursion', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('max_adverse_excursion', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('price_at_expiry', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signal_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signal_results_signal_id'), ['signal_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signal_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signal_results_signal_id'))

    op.drop_table('signal_results')
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signals_status'))
        batch_op.drop_index(batch_op.f('ix_signals_instrument_id'))

    op.drop_table('signals')
    with op.batch_alter_table('price_data', schema=None) as batch_op:
        batch_op.drop_index('ix_price_data_timestamp')
        batch_op.drop_index('ix_price_data_instrument_timeframe')
        batch_op.drop_index(batch_op.f('ix_price_data_instrument_id'))

    op.drop_table('price_data')
    op.drop_table('accuracy_stats')
    with op.batch_alter_table('news_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_news_events_published_at'))

    op.drop_table('news_events')
    op.drop_table('macro_data')
    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instruments_symbol'))

    op.drop_table('instruments')
    # ### end Alembic commands ###
