"""CompositeScoreStrategy — default backtest strategy (TASK-V7-20).

Wraps the existing composite-score signal-generation logic that was previously
inlined in BacktestEngine._generate_signal_fast().  The strategy delegates
back to the engine method so the actual computation stays in one place and
backward compatibility is guaranteed.
"""

import logging
from typing import TYPE_CHECKING, Optional

from src.backtesting.strategies.base import BaseStrategy

if TYPE_CHECKING:
    pass

logger = logging.getLogger(__name__)


class CompositeScoreStrategy(BaseStrategy):
    """Composite-score threshold strategy (original BacktestEngine logic).

    Entry signal is generated by BacktestEngine._generate_signal_fast() using
    pre-computed TA arrays.  This strategy is a thin adapter so that the engine
    can call strategy.check_entry(context) and get the same result as before.

    Backward-compatibility guarantee: with strategy="composite" the backtest
    produces bit-for-bit identical results to the pre-V7-20 engine.
    """

    def name(self) -> str:
        return "composite"

    def check_entry(self, context: dict) -> Optional[dict]:
        """Delegate to BacktestEngine._generate_signal_fast() via context.

        BacktestEngine passes a special "_engine" key in the context so that
        the strategy can call back into the engine's existing method without
        duplicating any logic.

        Expected context keys beyond the base spec:
            _engine         — BacktestEngine instance (for _generate_signal_fast)
            ta_score        — float, pre-computed TA score at current bar
            atr_value       — float or None
            regime          — str
            ta_indicators   — dict of scalar TA values
            symbol          — str
            market_type     — str
            timeframe       — str
            df              — pd.DataFrame slice (for S/R)
            candle_idx      — int (current candle index in main loop)
            sr_cache        — dict (mutable S/R cache, shared across calls)
        """
        engine = context.get("_engine")
        if engine is None:
            logger.error(
                "[CompositeScoreStrategy] '_engine' not found in context — "
                "cannot generate signal"
            )
            return None

        return engine._generate_signal_fast(
            ta_score=context["ta_score"],
            atr_value=context.get("atr_value"),
            regime=context["regime"],
            ta_indicators_at_i=context.get("ta_indicators", {}),
            symbol=context["symbol"],
            market_type=context["market_type"],
            timeframe=context["timeframe"],
            df_slice=context.get("df"),
            candle_idx=context.get("candle_idx", 0),
            sr_cache=context.get("sr_cache"),
        )
