global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: "market-analyzer-app"
    static_configs:
      - targets: ["app:8000"]
    metrics_path: /metrics
    scrape_interval: 10s

  - job_name: "finbert"
    static_configs:
      - targets: ["finbert:8001"]
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: "postgres"
    static_configs:
      - targets: ["postgres:5432"]
    scrape_interval: 30s

  - job_name: "redis"
    static_configs:
      - targets: ["redis:6379"]
    scrape_interval: 30s
